import { writeFileSync } from "node:fs";
import { runBatteryApp } from "@/lib/battery-app";
import { computeBatteryAlternatives } from "@/lib/battery-app/capacityAlternatives";
import { customerEconomyFromResult } from "@/lib/battery-app/customerEconomy";
import { buildDocDefinition } from "@/lib/report/docDefinition";
import { buildReportModel } from "@/lib/report/reportModel";
import { createInitialState } from "@/state/wizard";

const s = structuredClone(createInitialState());
s.consumption.profileId = "evening-heavy";
s.consumption.annualKwh = 20000;
s.production.mode = "manual";
s.production.annualKwh = 10000;
console.log("running engine...");
const outcome = runBatteryApp(s);
if (outcome.status !== "ok") throw new Error("not ok");
console.log("engine done");
const ce = customerEconomyFromResult(outcome.result, s.preferences.customerAncillaryShare);
const alts = computeBatteryAlternatives(outcome.input, outcome.result, s.preferences.customerAncillaryShare);
console.log("alts done");
const model = buildReportModel({ outcome, language: "sv", customerEconomy: ce, targetPaybackYears: 10, alternatives: alts, now: new Date(2026, 8, 10), reportId: "MBD-20260910-QA001" });
const dd = buildDocDefinition(model);
console.log("model done");
const pdfmake: any = (await import("pdfmake/build/pdfmake")).default;
const fonts: any = await import("pdfmake/build/vfs_fonts");
pdfmake.addVirtualFileSystem(fonts.default ?? fonts);
const buf: Buffer = await new Promise((res) => pdfmake.createPdf(dd).getBuffer((b: Buffer) => res(b)));
writeFileSync("/tmp/qa.pdf", buf);
console.log("pdf written", buf.length);
