import { getCalculation } from "@/lib/access/calculationCache";
import { createInitialState } from "@/state/wizard";
const s: any = JSON.parse(JSON.stringify(createInitialState("SE")));
s.grid.mainFuseA = 200;
s.consumption.mode = "annual";
s.consumption.annualKwh = 0;
s.consumption.profileId = "normal";
s.production.none = true;
s.strategies = { ...s.strategies, solarSelfConsumption: false, peakShaving: false, ancillary: true };
s.economy = { ...s.economy, paybackYears: 10 };
const r: any = getCalculation(s);
console.log(JSON.stringify({ ok: r.ok, cap: r.result?.recommendation?.capacityKWh, kw: r.result?.recommendation?.recommendedPowerKw }, null, 1));
console.log(Object.keys(r));
console.log(JSON.stringify(r).slice(0,1200));
