/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BatteriRouteImport } from './routes/batteri'
import { Route as BetalvaggRouteImport } from './routes/betalvagg'
import { Route as EkonomiRouteImport } from './routes/ekonomi'
import { Route as ForbrukningRouteImport } from './routes/forbrukning'
import { Route as HistorikRouteImport } from './routes/historik'
import { Route as InstallningarRouteImport } from './routes/installningar'
import { Route as NatRouteImport } from './routes/nat'
import { Route as ProduktionRouteImport } from './routes/produktion'
import { Route as ResultatRouteImport } from './routes/resultat'
import { Route as ApiPublicExtractMonthlyRouteImport } from './routes/api/public/extract-monthly'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatteriRoute = BatteriRouteImport.update({
  id: '/batteri',
  path: '/batteri',
  getParentRoute: () => rootRouteImport,
} as any)
const BetalvaggRoute = BetalvaggRouteImport.update({
  id: '/betalvagg',
  path: '/betalvagg',
  getParentRoute: () => rootRouteImport,
} as any)
const EkonomiRoute = EkonomiRouteImport.update({
  id: '/ekonomi',
  path: '/ekonomi',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbrukningRoute = ForbrukningRouteImport.update({
  id: '/forbrukning',
  path: '/forbrukning',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorikRoute = HistorikRouteImport.update({
  id: '/historik',
  path: '/historik',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallningarRoute = InstallningarRouteImport.update({
  id: '/installningar',
  path: '/installningar',
  getParentRoute: () => rootRouteImport,
} as any)
const NatRoute = NatRouteImport.update({
  id: '/nat',
  path: '/nat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktionRoute = ProduktionRouteImport.update({
  id: '/produktion',
  path: '/produktion',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultatRoute = ResultatRouteImport.update({
  id: '/resultat',
  path: '/resultat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtractMonthlyRoute = ApiPublicExtractMonthlyRouteImport.update({
  id: '/api/public/extract-monthly',
  path: '/api/public/extract-monthly',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batteri': typeof BatteriRoute
  '/betalvagg': typeof BetalvaggRoute
  '/ekonomi': typeof EkonomiRoute
  '/forbrukning': typeof ForbrukningRoute
  '/historik': typeof HistorikRoute
  '/installningar': typeof InstallningarRoute
  '/nat': typeof NatRoute
  '/produktion': typeof ProduktionRoute
  '/resultat': typeof ResultatRoute
  '/api/public/extract-monthly': typeof ApiPublicExtractMonthlyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/batteri': typeof BatteriRoute
  '/betalvagg': typeof BetalvaggRoute
  '/ekonomi': typeof EkonomiRoute
  '/forbrukning': typeof ForbrukningRoute
  '/historik': typeof HistorikRoute
  '/installningar': typeof InstallningarRoute
  '/nat': typeof NatRoute
  '/produktion': typeof ProduktionRoute
  '/resultat': typeof ResultatRoute
  '/api/public/extract-monthly': typeof ApiPublicExtractMonthlyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batteri': typeof BatteriRoute
  '/betalvagg': typeof BetalvaggRoute
  '/ekonomi': typeof EkonomiRoute
  '/forbrukning': typeof ForbrukningRoute
  '/historik': typeof HistorikRoute
  '/installningar': typeof InstallningarRoute
  '/nat': typeof NatRoute
  '/produktion': typeof ProduktionRoute
  '/resultat': typeof ResultatRoute
  '/api/public/extract-monthly': typeof ApiPublicExtractMonthlyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/batteri'
    | '/betalvagg'
    | '/ekonomi'
    | '/forbrukning'
    | '/historik'
    | '/installningar'
    | '/nat'
    | '/produktion'
    | '/resultat'
    | '/api/public/extract-monthly'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/batteri'
    | '/betalvagg'
    | '/ekonomi'
    | '/forbrukning'
    | '/historik'
    | '/installningar'
    | '/nat'
    | '/produktion'
    | '/resultat'
    | '/api/public/extract-monthly'
  id:
    | '__root__'
    | '/'
    | '/batteri'
    | '/betalvagg'
    | '/ekonomi'
    | '/forbrukning'
    | '/historik'
    | '/installningar'
    | '/nat'
    | '/produktion'
    | '/resultat'
    | '/api/public/extract-monthly'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatteriRoute: typeof BatteriRoute
  BetalvaggRoute: typeof BetalvaggRoute
  EkonomiRoute: typeof EkonomiRoute
  ForbrukningRoute: typeof ForbrukningRoute
  HistorikRoute: typeof HistorikRoute
  InstallningarRoute: typeof InstallningarRoute
  NatRoute: typeof NatRoute
  ProduktionRoute: typeof ProduktionRoute
  ResultatRoute: typeof ResultatRoute
  ApiPublicExtractMonthlyRoute: typeof ApiPublicExtractMonthlyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batteri': {
      id: '/batteri'
      path: '/batteri'
      fullPath: '/batteri'
      preLoaderRoute: typeof BatteriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betalvagg': {
      id: '/betalvagg'
      path: '/betalvagg'
      fullPath: '/betalvagg'
      preLoaderRoute: typeof BetalvaggRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ekonomi': {
      id: '/ekonomi'
      path: '/ekonomi'
      fullPath: '/ekonomi'
      preLoaderRoute: typeof EkonomiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbrukning': {
      id: '/forbrukning'
      path: '/forbrukning'
      fullPath: '/forbrukning'
      preLoaderRoute: typeof ForbrukningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historik': {
      id: '/historik'
      path: '/historik'
      fullPath: '/historik'
      preLoaderRoute: typeof HistorikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installningar': {
      id: '/installningar'
      path: '/installningar'
      fullPath: '/installningar'
      preLoaderRoute: typeof InstallningarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nat': {
      id: '/nat'
      path: '/nat'
      fullPath: '/nat'
      preLoaderRoute: typeof NatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produktion': {
      id: '/produktion'
      path: '/produktion'
      fullPath: '/produktion'
      preLoaderRoute: typeof ProduktionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultat': {
      id: '/resultat'
      path: '/resultat'
      fullPath: '/resultat'
      preLoaderRoute: typeof ResultatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extract-monthly': {
      id: '/api/public/extract-monthly'
      path: '/api/public/extract-monthly'
      fullPath: '/api/public/extract-monthly'
      preLoaderRoute: typeof ApiPublicExtractMonthlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatteriRoute: BatteriRoute,
  BetalvaggRoute: BetalvaggRoute,
  EkonomiRoute: EkonomiRoute,
  ForbrukningRoute: ForbrukningRoute,
  HistorikRoute: HistorikRoute,
  InstallningarRoute: InstallningarRoute,
  NatRoute: NatRoute,
  ProduktionRoute: ProduktionRoute,
  ResultatRoute: ResultatRoute,
  ApiPublicExtractMonthlyRoute: ApiPublicExtractMonthlyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
